baseURL = "http://localhost"
languageCode = "en-us"
title = "Demo"
disableKinds = ["home", "taxonomy", "taxonomyTerm", "sitemap"]
[mediaTypes]
  [mediaTypes."application/x-php"]
    suffixes = ["php"]
[outputFormats]
  [outputFormats.PHP]
    mediaType = "application/x-php"
    baseName = "index"
    isPlainText = true
[outputs]
  page = ["php"]
